# Generated by Django 4.2.11 on 2024-07-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_customuser_remove_property_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
