# Generated by Django 4.2.11 on 2024-07-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_cover_image_propertyvideo_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
